spring.application.name=andrey-churavskiy-trainee-task-1

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
stripe.api.key=sk_test_51Rl6bAPmOv9XydwICEM4i4GQIZkKieXh8tskTRNCATCUfnNbrRoEJ7evRwxuDfT6Rl73MwySXEO7SDvU6WbFfNKH005n0PnFe3
stripe.cancel-url=https://localhost/cancel
stripe.success-url=https://localhost/success

server.port=8080